import { notFound } from "next/navigation";
import { getPosts } from "@/lib/content/posts";
import { markdownToHtml } from "@/lib/markdown";
import { siteConfig } from "@/lib/site-config";
import { ReadingTools } from "@/components/reading-tools";
import Image from "next/image";
export async function generateStaticParams() { return getPosts().map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const post = getPosts().find((item) => item.slug === slug); return post ? { title: post.title, description: post.description, alternates: { canonical: post.canonical || `${siteConfig.url}/posts/${post.slug}` }, openGraph: { title: post.title, description: post.description, type: "article", publishedTime: post.date, modifiedTime: post.updated ?? post.date } } : {}; }
export default async function PostPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const posts = getPosts(); const index = posts.findIndex((item) => item.slug === slug); const post = posts[index]; if (!post) notFound(); const html = await markdownToHtml(post.content); const structuredData = { "@context": "https://schema.org", "@type": "BlogPosting", headline: post.title, description: post.description, datePublished: post.date, dateModified: post.updated ?? post.date, author: { "@type": "Person", name: siteConfig.author }, mainEntityOfPage: `${siteConfig.url}/posts/${post.slug}` }; return <article className="page post-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} /><span className="eyebrow">Essay</span><h1>{post.title}</h1><div className="meta"><time>{post.date}</time>{post.updated && ` · 更新于 ${post.updated}`} · {post.wordCount} 字</div>{post.cover && <Image className="post-cover" src={post.cover} alt="" width={1200} height={630} priority />}{<ReadingTools html={html} />}<div className="section"><strong>{post.title}</strong><p>本文作者：{siteConfig.author} · 内容采用 {siteConfig.contentLicense} 许可。</p><small>转载时请保留作者与原文链接，商业使用请先联系作者。</small></div><div>{post.tags.map((tag) => <span className="tag" key={tag}>#{tag}</span>)}</div><nav className="post-nav" aria-label="文章导航">{posts[index + 1] && <a href={`/posts/${posts[index + 1].slug}`}>← {posts[index + 1].title}</a>}{posts[index - 1] && <a href={`/posts/${posts[index - 1].slug}`}>{posts[index - 1].title} →</a>}</nav></article>; }
